# SEO settings
title: Xin Shi
description: "Dr Xin Shi's Personal website "
keywords: "PhD, Science, Nanopore, Single molecule, XinShi, Nanoscience, Biophysics"
url: http://xinshi.me
baseurl: ""

# google_analytics: UA-52446115-1
# repo: http://github.com/nandomoreirame/end2end
# disqus_shortname: "nandothemes"
# disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Xin Shi
  job: Postdoctoral researcher 
  bio: "@ Cees Dekker Lab, TU Delft"
  thumb: /assets/images/author_photo.jpg
  email: x.shi@tudelft.nm
  url: https://xinshi.me/
  orcid: https://orcid.org/0000-0002-7382-5519
  twitter: https://twitter.com/Dan_ShiXin
  researchgate: https://www.researchgate.net/profile/Xin_Shi13
  google-scholar: https://scholar.google.com/citations?hl=en&user=cdvqdJwAAAAJ




# social links
# twitter_username: jekyllrb
# github_username:  jekyll
# rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
# youtube_channel_name: CloudCannon
# telegram_username: jekyll
# googleplus_username: +jekyll
# microdotblog_username: jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
