# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  sort_reverse: true
  per_page: 5
  permalink: "/page/:num/"

comments: false

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Xin Shi
description: "Dr Xin Shi's Personal website "
keywords: "PhD, Science, Nanopore, Single molecule, XinShi, Nanoscience, Biophysics"
url: http://xinshi.me
baseurl: ""

# google_analytics: UA-52446115-1
# repo: http://github.com/nandomoreirame/end2end
# disqus_shortname: "nandothemes"
# disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Xin Shi
  job: Postdoctoral reseacher 
  bio: "@ Cees Dekker Lab, TU Delft"
  thumb: /images/author_photo.jpg
  email: x.shi@tudelft.nm
  url: https://xinshi.me/
  orcid: https://orcid.org/0000-0002-7382-5519
  twitter: https://twitter.com/Dan_ShiXin
  researchgate: https://www.researchgate.net/profile/Xin_Shi13
  google-scholar: https://scholar.google.com/citations?hl=en&user=cdvqdJwAAAAJ

# navbar pages
navbar:
  - slug: research
    title: Research
  - slug: blog
    title: Blog
  - slug: about
    title: About Me

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
